services:
  janus:
    build: ./janus
    ports:
      - "8989:8989"
      - "10000-10200:10000-10200/udp"  # WebRTC media (UDP)
    networks:
      - janusnet      
    volumes:
      - ./certs:/certs:ro
      - ./janus/conf/janus.jcfg:/opt/janus/etc/janus/janus.jcfg
      - ./janus/conf/janus.transport.websockets.jcfg:/opt/janus/etc/janus/janus.transport.websockets.jcfg
      - ./janus/conf/janus.plugin.videoroom.jcfg:/opt/janus/etc/janus/janus.plugin.videoroom.jcfg
      
  web:
    build: ./web
    ports:
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./web/html:/usr/share/nginx/html:ro      
    networks:
      - janusnet
      
networks:
  janusnet:
    driver: bridge      
